name: home_art
description: "هوم آرت — تطبيق تسويق وبيع أونلاين للأثاث والديكور الفاخر"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Theme
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  iconsax_flutter: ^1.0.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Navigation
  go_router: ^14.2.7

  # Local Storage
  shared_preferences: ^2.3.2

  # Utils
  intl: any
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "App_Assets/logo/homeart-logo-dark.png"
  adaptive_icon_background: "#F4EFE5"
  adaptive_icon_foreground: "App_Assets/logo/homeart-logo-dark1.png"

# Splash Screen Configuration
flutter_native_splash:
  color: "#17130F"
  image: "App_Assets/logo/homeart-logo-lite.png"
  android: true
  ios: false

flutter:
  uses-material-design: true
  assets:
    - App_Assets/
    - App_Assets/logo/
    - assets/images/products/
    - assets/images/inspirations/
    - assets/images/banners/
    - assets/icons/
